---
debug: false
verbose: false
modules-search: [ local ]
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - users
  - displaymanager
  - bootloader
  - initramfs
  - umount
- show:
  - finished
branding: dragonos
prompt-install: false
